'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('fiscocont', {
  login: (senha) => ipcRenderer.invoke('auth:login', senha),
  pickPdf: () => ipcRenderer.invoke('balancete:pick'),
  pickMultiplePdf: () => ipcRenderer.invoke('balancete:pickMultiple'),
  processPdf: (p) => ipcRenderer.invoke('balancete:process', p),
  processLote: (paths) => ipcRenderer.invoke('balancete:processLote', paths),
  exportPdf: (sugestao) => ipcRenderer.invoke('balancete:exportPdf', sugestao),
  exportInvertidas: (sugestao) => ipcRenderer.invoke('balancete:exportInvertidas', sugestao),
  exportBalanceteCompleto: (sugestao) => ipcRenderer.invoke('balancete:exportBalanceteCompleto', sugestao),
  enviarMensagemIA: (mensagem, historico) => ipcRenderer.invoke('ia:enviarMensagem', { mensagem, historico }),
  conciliacao: {
    pickPlanoContas: () => ipcRenderer.invoke('conciliacao:pickPlanoContas'),
    pickExtrato: () => ipcRenderer.invoke('conciliacao:pickExtrato'),
    conciliar: (banco, extratoPath, ano) => ipcRenderer.invoke('conciliacao:conciliar', { banco, extratoPath, ano }),
    pickTxtOriginal: () => ipcRenderer.invoke('conciliacao:pickTxtOriginal'),
    exportarTxt: (txtOriginalPath, mapa, sugestao) => ipcRenderer.invoke('conciliacao:exportarTxt', { txtOriginalPath, mapa, sugestao }),
  },
  exportDreCompleta: (fmt, sugestao, cliente) => ipcRenderer.invoke('balancete:exportDreCompleta', { fmt, sugestao, cliente }),
  indicadoresHtml: () => ipcRenderer.invoke('contabil:indicadoresHtml'),
  exportIndicadores: (sugestao) => ipcRenderer.invoke('contabil:exportIndicadores', sugestao),
  cloud: {
    status: () => ipcRenderer.invoke('cloud:status'),
    setup: () => ipcRenderer.invoke('cloud:setup'),
    lastSync: () => ipcRenderer.invoke('cloud:lastSync'),
    onSynced: (cb) => ipcRenderer.on('cloud:synced', (_e, d) => cb(d)),
    listEmpresas: () => ipcRenderer.invoke('cloud:listEmpresas'),
    listHistorico: (cnpj) => ipcRenderer.invoke('cloud:listHistorico', cnpj),
    getHistoricoItem: (cnpj, id) => ipcRenderer.invoke('cloud:getHistoricoItem', { cnpj, id }),
    deleteHistoricoItem: (cnpj, id) => ipcRenderer.invoke('cloud:deleteHistoricoItem', { cnpj, id }),
  },
  license: {
    check: () => ipcRenderer.invoke('license:check'),
    listAll: () => ipcRenderer.invoke('license:listAll'),
    setStatus: (codigo, status) => ipcRenderer.invoke('license:setStatus', { codigo, status }),
    onChanged: (cb) => ipcRenderer.on('license:changed', (_evt, data) => cb(data)),
    onRealtimeStatus: (cb) => ipcRenderer.on('license:realtimeStatus', (_evt, data) => cb(data)),
    getRealtimeStatus: () => ipcRenderer.invoke('license:getRealtimeStatus'),
  },
  changelog: {
    check: () => ipcRenderer.invoke('changelog:check'),
    marcarVisto: (versao) => ipcRenderer.invoke('changelog:marcarVisto', versao),
  },
  tema: {
    get: () => ipcRenderer.invoke('tema:get'),
    set: (nome) => ipcRenderer.invoke('tema:set', nome),
  },
  updater: {
    installNow: () => ipcRenderer.invoke('updater:installNow'),
    onAvailable: (cb) => ipcRenderer.on('updater:available', (_e, d) => cb(d)),
    onReady: (cb) => ipcRenderer.on('updater:ready', (_e, d) => cb(d)),
  },
  fiscal: {
    pickSped: () => ipcRenderer.invoke('fiscal:pickSped'),
    visualizarSped: (spedPath) => ipcRenderer.invoke('fiscal:visualizarSped', spedPath),
    corrigirSped: (spedPath, cestInvalidos) => ipcRenderer.invoke('fiscal:corrigirSped', { spedPath, cestInvalidos }),
    corrigirSpedDashboard: (spedPath) => ipcRenderer.invoke('fiscal:corrigirSpedDashboard', spedPath),
    substituirLmc: (semLmcPath, comLmcPath) => ipcRenderer.invoke('fiscal:substituirLmc', { semLmcPath, comLmcPath }),
    pickPfx: () => ipcRenderer.invoke('fiscal:pickPfx'),
    certValidar: (pfxPath, senha) => ipcRenderer.invoke('fiscal:certValidar', { pfxPath, senha }),
    certSalvar: (pfxPath, senha, info) => ipcRenderer.invoke('fiscal:certSalvar', { pfxPath, senha, info }),
    certListar: () => ipcRenderer.invoke('fiscal:certListar'),
    certRemover: (id) => ipcRenderer.invoke('fiscal:certRemover', id),
    pickPastaBase: () => ipcRenderer.invoke('fiscal:pickPastaBase'),
    pastaBaseGet: () => ipcRenderer.invoke('fiscal:pastaBaseGet'),
    nfseBaixar: (empresaId, dataInicial, dataFinal) => ipcRenderer.invoke('fiscal:nfseBaixar', { empresaId, dataInicial, dataFinal }),
    nfseAnalise: (empresaId, dataInicial, dataFinal) => ipcRenderer.invoke('fiscal:nfseAnalise', { empresaId, dataInicial, dataFinal }),
    nfseExportarHtml: (html, tipo, empresaNome) => ipcRenderer.invoke('fiscal:nfseExportarHtml', { html, tipo, empresaNome }),
    lmcDashboard: (semLmcPath, comLmcPath) => ipcRenderer.invoke('fiscal:lmcDashboard', { semLmcPath, comLmcPath }),
    baixarSpedLmc: () => ipcRenderer.invoke('fiscal:baixarSpedLmc'),
    visualizarSpedCorrigido: () => ipcRenderer.invoke('fiscal:visualizarSpedCorrigido'),
    baixarSpedCorrigido: () => ipcRenderer.invoke('fiscal:baixarSpedCorrigido'),
    pickXmlsFolder: () => ipcRenderer.invoke('fiscal:pickXmlsFolder'),
    dashboard: (spedPath) => ipcRenderer.invoke('fiscal:dashboard', spedPath),
    documentos: (spedPath) => ipcRenderer.invoke('fiscal:documentos', spedPath),
    conferencia: (spedPath, xmlsPath) => ipcRenderer.invoke('fiscal:conferencia', { spedPath, xmlsPath }),
    conferenciaSaidas: (spedPath, xmlsPath) => ipcRenderer.invoke('fiscal:conferenciaSaidas', { spedPath, xmlsPath }),
    prepararInclusao: (spedPath, xmlsPath) => ipcRenderer.invoke('fiscal:prepararInclusao', { spedPath, xmlsPath }),
    incluirNotas: (spedPath, notas, sugestao) => ipcRenderer.invoke('fiscal:incluirNotas', { spedPath, notas, sugestao }),
    desoneracao: (xmlsPath) => ipcRenderer.invoke('fiscal:desoneracao', { xmlsPath }),
    icmsCredito: (spedPath, xmlsPath) => ipcRenderer.invoke('fiscal:icmsCredito', { spedPath, xmlsPath }),
    listarNotasXml: (xmlsPath) => ipcRenderer.invoke('fiscal:listarNotasXml', xmlsPath),
    gerarDanfe: (xmlsPath, chave) => ipcRenderer.invoke('fiscal:gerarDanfe', { xmlsPath, chave }),
    frete: (spedPath, xmlsPath) => ipcRenderer.invoke('fiscal:frete', { spedPath, xmlsPath }),
    classificacao: (spedPath) => ipcRenderer.invoke('fiscal:classificacao', { spedPath }),
    pickPgdas: () => ipcRenderer.invoke('fiscal:pickPgdas'),
    pgdas: (pdfPath) => ipcRenderer.invoke('fiscal:pgdas', pdfPath),
    export: (fmt, payload) => ipcRenderer.invoke('fiscal:export', { fmt, payload }),
  },
  openPath: (p) => ipcRenderer.invoke('app:openPath', p),
  diag: () => ipcRenderer.invoke('app:diag'),
  version: () => ipcRenderer.invoke('app:version'),
  win: {
    minimize: () => ipcRenderer.send('win:minimize'),
    maximize: () => ipcRenderer.send('win:maximize'),
    close: () => ipcRenderer.send('win:close'),
    isMaximized: () => ipcRenderer.invoke('win:isMaximized'),
    onMaximize: (cb) => ipcRenderer.on('win:maximized', (_e, v) => cb(v)),
  },
});
